# Generated by Django 4.2.6 on 2023-10-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='porcetagem_comissao',
            new_name='porcentagem_comissao',
        ),
    ]
